version: '3.9'

services:
  frontend:
    build:
      context: ./everzero-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Assuming your frontend runs on port 3000
    depends_on:
      - gateway
    environment:
      - API_URL=http://gateway  # Update this URL to match the backend service
    networks:
      - everzero_network
  
  gateway:
    build:
        context: ./deployable
        dockerfile: Gateway/Dockerfile
    ports:
        - "80:80"
        - "443:443"
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
      
  
  # Dependencies
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=SecureNotes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - everzero_network

networks:
  everzero_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
