version: '3.9'

services:
  frontend:
    build:
      context: ./deployable/everzero-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://gateway
    networks:
      - extranet
    #depends_on:
      #- gateway

networks:
  intranet:
    driver: bridge
    internal: true
  extranet:
    driver: bridge

volumes:
  auth_db_data:
    driver: local
  invoice_db_data:
    driver: local
  emission_db_data:
    driver: local
